using System.Text.Json.Serialization;
using MeuCrudCsharp.Features.Profiles.Admin.Dtos;

namespace MeuCrudCsharp.Features.Plans.DTOs
{
    /// <summary>
    /// Represents the detailed response for a subscription plan from the payment provider (e.g., Mercado Pago).
    /// </summary>
    public class PlanResponseDto
    {
        /// <summary>
        /// The unique identifier of the plan generated by the payment provider.
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name or reason for the subscription plan.
        /// </summary>
        [JsonPropertyName("reason")]
        public string? Reason { get; set; }

        /// <summary>
        /// The current status of the plan (e.g., "active", "cancelled").
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get; set; }

        /// <summary>
        /// The date and time when the plan was created.
        /// </summary>
        [JsonPropertyName("date_created")]
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// The external identifier provided by our system during plan creation.
        /// This is used to link the provider's plan to a local record.
        /// </summary>
        [JsonPropertyName("external_reference")]
        public string? ExternalPlanId { get; set; }

        /// <summary>
        /// Contains the details of the recurring payment, such as frequency and amount.
        /// </summary>
        [JsonPropertyName("auto_recurring")]
        public AutoRecurringDto? AutoRecurring { get; set; }
    }
}
