using System.ComponentModel.DataAnnotations;

namespace MeuCrudCsharp.Features.Profiles.UserAccount.DTOs
{
    /// <summary>
    /// Represents the data required to update the payment card associated with a user's subscription.
    /// </summary>
    public class UpdateCardTokenDto
    {
        /// <summary>
        /// The new card token generated by the payment provider's frontend SDK (e.g., Mercado Pago's Card Token).
        /// </summary>
        [Required(ErrorMessage = "The new card token is required.")]
        public string? NewCardToken { get; set; }
    }
}
