using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace MeuCrudCsharp.Features.Subscriptions.DTOs
{
    /// <summary>
    /// Represents the data required to create a new subscription with the payment provider.
    /// </summary>
    public class CreateSubscriptionDto
    {
        /// <summary>
        /// The unique identifier of the pre-approval plan the user is subscribing to.
        /// </summary>
        [JsonPropertyName("preapproval_plan_id")]
        [Required(ErrorMessage = "The plan ID is required.")]
        public string? PreapprovalPlanId { get; set; }

        /// <summary>
        /// The email address of the person paying for the subscription.
        /// </summary>
        [JsonPropertyName("payer_email")]
        [Required(ErrorMessage = "The payer's email is required.")]
        [EmailAddress(ErrorMessage = "The payer's email must be a valid email address.")]
        public string? PayerEmail { get; set; }

        /// <summary>
        /// The one-time use token representing the payment card, generated by the frontend SDK.
        /// </summary>
        [JsonPropertyName("card_token_id")]
        [Required(ErrorMessage = "The card token is required.")]
        public string? CardTokenId { get; set; }

        /// <summary>
        /// The URL to which the user will be redirected after the subscription flow.
        /// </summary>
        [JsonPropertyName("back_url")]
        [Url(ErrorMessage = "The back URL must be a valid URL.")]
        public string? BackUrl { get; set; }
    }
}
