services:
  # --- Serviço do Redis ---
  redis:
    image: "redis:alpine"
    container_name: meu-servidor-redis
    ports:
      - "6379:6379"

  # --- Serviço da sua Aplicação Web ---
  webapp:
    container_name: minha-aplicacao-aspnet
    build: . # Diz ao Compose para usar o Dockerfile nesta pasta para construir a imagem
    ports:
      - "8080:8080"
    env_file:
      - .env # Aponta para o ficheiro que contém os segredos
    environment:
      # As variáveis abaixo são APENAS REFERÊNCIAS.
      # Os valores reais serão lidos do ficheiro .env.
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - MercadoPago__AccessToken=${MercadoPago__AccessToken}
      - MercadoPago__WebhookSecret=${MercadoPago__WebhookSecret}
      - MercadoPago__PublicKey=${MercadoPago__PublicKey}
      - Jwt__Key=${Jwt__Key}
      - Google__ClientId=${Google__ClientId}
      - Google__ClientSecret=${Google__ClientSecret}
      - SendGrid__ApiKey=${SendGrid__ApiKey}
      - SendGrid__FromEmail=${SendGrid__FromEmail}
      - SendGrid__FromName=${SendGrid__FromName}
    depends_on:
      - redis

