# docker-compose.yml
version: '3.8'

services:
  # Serviço 1: Nosso servidor Redis
  redis:
    image: "redis:alpine" # Puxa a imagem oficial e leve do Redis
    container_name: meu-servidor-redis

  # Serviço 2: Nossa aplicação ASP.NET
  webapp:
    container_name: minha-aplicacao-aspnet
    # 'build: .' diz para construir a imagem a partir do Dockerfile local
    build: .
    ports:
      # Expõe a porta 8080 do contêiner para a porta 8080 da sua máquina
      - "8080:8080"
    environment:
      # AQUI ESTÁ A MÁGICA DA CONEXÃO!
      # Passamos a string de conexão para a aplicação.
      # O Docker Compose cria uma rede onde o nome 'redis' é resolvido para o IP do contêiner do Redis.
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      # Garante que o contêiner do Redis seja iniciado ANTES da nossa aplicação
      - redis