services:
  # ... serviço do redis (sem mudanças) ...
  redis:
    image: "redis:alpine"
    container_name: meu-servidor-redis
    ports:
      - "6379:6379"

  webapp:
    container_name: minha-aplicacao-aspnet
    build: .
    ports:
      - "8080:8080"
    environment:
      # --- Configurações da Aplicação e Conexões ---
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_URLS=http://+:8080

      # --- Segredos Lidos do Arquivo .env ---
      # JWT
      - Jwt__Key=${JWT_SECRET_KEY}

      # Google
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - Google__ClientSecret=${GOOGLE_CLIENT_SECRET}

      # Mercado Pago
      - MercadoPago__AccessToken=${MERCADOPAGO_ACCESS_TOKEN}
      - MercadoPago__WebhookSecret=${MERCADOPAGO_WEBHOOK_SECRET}

      # SendGrid
      - SendGrid__ApiKey=${SENDGRID_API_KEY}
      - SendGrid__FromEmail=${SENDGRID_FROM_EMAIL}
      - SendGrid__FromName=${SENDGRID_FROM_NAME}
    depends_on:
      - redis

