using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace MeuCrudCsharp.Features.Videos.DTOs
{
    /// <summary>
    /// Represents the data required to create the metadata for a new video.
    /// This DTO is typically sent after the video file has been uploaded and a storage identifier has been generated.
    /// </summary>
    public class CreateVideoDto
    {
        /// <summary>
        /// The title of the video.
        /// </summary>
        [Required(ErrorMessage = "The title is required.")]
        [StringLength(200, ErrorMessage = "The title cannot be longer than 200 characters.")]
        public string? Title { get; set; }

        /// <summary>
        /// An optional, brief description of the video's content.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// The unique identifier for the video's files in the storage system.
        /// This is typically the GUID generated by the upload endpoint.
        /// </summary>
        [Required(ErrorMessage = "The storage identifier is required.")]
        public string? StorageIdentifier { get; set; }

        /// <summary>
        /// The name of the course this video belongs to.
        /// </summary>
        [Required(ErrorMessage = "The course name is required.")]
        public string? CourseName { get; set; }

        /// <summary>
        /// The thumbnail image file for the video.
        /// </summary>
        [Required(ErrorMessage = "A thumbnail file is required.")]
        public IFormFile? ThumbnailFile { get; set; }

        /// <summary>
        /// The original filename of the uploaded video file (e.g., "my-vacation.mp4").
        /// </summary>
        [Required(ErrorMessage = "The original file name is required.")]
        public string? OriginalFileName { get; set; } // ✅ ADICIONE ESTA PROPRIEDADE
    }
}
